require "InventoryTags/InventoryTags_Core"
local IT=InventoryTags
local fallback={
    ["EN"] = {
        ["Categories"] = "Categories",
        ["Sort"] = "Sort",
        ["Auto"] = "Auto Pack",
        ["All"] = "Select All",
        ["Default"] = "Vanilla",
        ["Quantity"] = "Quantity",
        ["Weight"] = "Weight",
        ["Time"] = "Time",
        ["Asc"] = "Ascending",
        ["Desc"] = "Descending",
        ["Project"] = "Inventory Tags",
        ["Bulk"] = "Bulk",
        ["None"] = "Deselect All",
        ["ConfirmAll"] = "Select all categories?",
        ["ConfirmNone"] = "Deselect all categories?",
        ["Confirm"] = "Confirm",
        ["Cancel"] = "Cancel",
        ["Partial"] = " (Partial)",
        ["GroupFood"] = "Food",
        ["GroupMedical"] = "Medical",
        ["GroupWeapons"] = "Weapons",
        ["GroupClothing"] = "Clothes",
        ["GroupTools"] = "Tools",
        ["GroupMaterials"] = "Materials",
        ["GroupLiterature"] = "Books",
        ["GroupElectronics"] = "Electronics",
        ["GroupVehicle"] = "Vehicles",
        ["GroupOutdoors"] = "Outdoors",
        ["GroupHousehold"] = "Household",
        ["GroupOther"] = "Other",
        ["GroupCooking"] = "Kitchenware",
        ["GroupContainers"] = "Containers",
        ["GroupEntertainment"] = "Entertainment",
        ["GroupToys"] = "Toys",
        ["Select"] = "Select",
        ["SelectMatches"] = "Select matching items",
        ["ClearSelection"] = "Clear selection",
        ["SelectionUnavailable"] = "Selection was not changed. Open the intended container and try again.",
        ["SelectionDragging"] = "Finish dragging before selecting by category.",
        ["SelectionMixedLimit"] = "A same-name stack mixes categories beyond the native visible-row limit. Selection was not changed; separate that stack first.",
    },
    ["CN"] = {
        ["Categories"] = "分类",
        ["Sort"] = "排序",
        ["Auto"] = "自动打包",
        ["All"] = "全选",
        ["Default"] = "原版",
        ["Quantity"] = "数量",
        ["Weight"] = "重量",
        ["Time"] = "时间",
        ["Asc"] = "升序",
        ["Desc"] = "降序",
        ["Project"] = "库存标签",
        ["Bulk"] = "批量",
        ["None"] = "全不选",
        ["ConfirmAll"] = "全选所有分类？",
        ["ConfirmNone"] = "取消所有分类？",
        ["Confirm"] = "确定",
        ["Cancel"] = "取消",
        ["Partial"] = "（部分）",
        ["GroupFood"] = "食物",
        ["GroupMedical"] = "医疗",
        ["GroupWeapons"] = "武器",
        ["GroupClothing"] = "衣服",
        ["GroupTools"] = "工具",
        ["GroupMaterials"] = "材料",
        ["GroupLiterature"] = "书籍",
        ["GroupElectronics"] = "电子",
        ["GroupVehicle"] = "车辆",
        ["GroupOutdoors"] = "户外",
        ["GroupHousehold"] = "家居",
        ["GroupOther"] = "其他",
        ["GroupCooking"] = "厨具",
        ["GroupContainers"] = "容器",
        ["GroupEntertainment"] = "娱乐",
        ["GroupToys"] = "玩具",
        ["Select"] = "选取",
        ["SelectMatches"] = "选中匹配物品",
        ["ClearSelection"] = "取消选取",
        ["SelectionUnavailable"] = "未更改选取。请打开目标容器后重试。",
        ["SelectionDragging"] = "请先结束拖动物品，再按分类选取。",
        ["SelectionMixedLimit"] = "同名堆叠混有不同分类，匹配物品超出原版可显示行数。本次未更改选取，请先拆分该堆叠。",
    },
    ["CH"] = {
        ["Categories"] = "分類",
        ["Sort"] = "排序",
        ["Auto"] = "自動打包",
        ["All"] = "全選",
        ["Default"] = "原版",
        ["Quantity"] = "數量",
        ["Weight"] = "重量",
        ["Time"] = "時間",
        ["Asc"] = "升序",
        ["Desc"] = "降序",
        ["Project"] = "庫存標籤",
        ["Bulk"] = "批量",
        ["None"] = "全不選",
        ["ConfirmAll"] = "全選所有分類？",
        ["ConfirmNone"] = "取消所有分類？",
        ["Confirm"] = "確定",
        ["Cancel"] = "取消",
        ["Partial"] = "（部分）",
        ["GroupFood"] = "食物",
        ["GroupMedical"] = "醫療",
        ["GroupWeapons"] = "武器",
        ["GroupClothing"] = "衣服",
        ["GroupTools"] = "工具",
        ["GroupMaterials"] = "材料",
        ["GroupLiterature"] = "書籍",
        ["GroupElectronics"] = "電子",
        ["GroupVehicle"] = "車輛",
        ["GroupOutdoors"] = "戶外",
        ["GroupHousehold"] = "家居",
        ["GroupOther"] = "其他",
        ["GroupCooking"] = "廚具",
        ["GroupContainers"] = "容器",
        ["GroupEntertainment"] = "娛樂",
        ["GroupToys"] = "玩具",
        ["Select"] = "選取",
        ["SelectMatches"] = "選中符合的物品",
        ["ClearSelection"] = "取消選取",
        ["SelectionUnavailable"] = "未更改選取。請開啟目標容器後重試。",
        ["SelectionDragging"] = "請先結束拖曳物品，再按分類選取。",
        ["SelectionMixedLimit"] = "同名堆疊混有不同分類，符合物品超出原版可顯示列數。本次未更改選取，請先拆分該堆疊。",
    },
}
function IT.language()
    local language=Translator and Translator.getLanguage() or nil
    local name=tostring(IT.call(language,"name") or "EN"):upper():gsub("%-","_")
    if name=="ZH_CN" or name=="ZH_HANS" or name=="ZH" then return "CN" end
    if name=="ZH_TW" or name=="ZH_HANT" then return "CH" end
    return name
end
function IT.text(id)
    local key="IGUI_InventoryTags_"..id
    local native=getTextOrNull and getTextOrNull(key) or getText(key)
    local lang=IT.language()
    local english=fallback.EN[id]
    if fallback[lang] and (not native or native==key or native==english) then
        return fallback[lang][id] or english or key
    end
    return native or english or key
end
